mp2/marketplace/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'marketplace'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/(?P<user_id>[0-9]+)/$', views.userdetails, name='userdetails'),
    url(r'^photo/(?P<post_id>[0-9]+)/$', views.photo, name='photo'),
    url(r'^offer/(?P<post_id>[0-9]+)/$', views.makeoffer, name='makeoffer'),
    url(r'^update/(?P<myoffer_id>[0-9]+)/$', views.updateoffer, name='updateoffer'),
    url(r'^approve/(?P<offer_id>[0-9]+)/$', views.approveoffer, name='approveoffer'),
    url(r'^reject/(?P<offer_id>[0-9]+)/$', views.rejectoffer, name='rejectoffer'),
    url(r'^delete/(?P<myoffer_id>[0-9]+)/$', views.canceloffer, name='canceloffer'),
    url(r'^results/condition/(?P<condition_name>[-\w ]+)/$', views.condresults, name='condresults'),
    url(r'^results/type/(?P<type_name>\w+)/$', views.typeresults, name='typeresults'),
    url(r'^results/course/(?P<course_name>[-\w ]+)/$', views.courseresults, name='courseresults'),
    url(r'^results/tags/(?P<tag_name>[-\w]+)/$', views.tagresults, name='tagresults'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mp2/mp2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('marketplace.urls')),
]

mp2/marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from taggit.managers import TaggableManager


degree_or_office = models.CharField(max_length=50)
degree_or_office.contribute_to_class(User, 'degree_or_office')


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='marketplace/static/marketplace/img/', blank=True, default='marketplace/static/marketplace/img/def/default.png')
    name = models.CharField(max_length=25)
    condition = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    CHOICES = (
        ('Academic', 'Academic'),
        ('Office', 'Office'),
    )
    type = models.CharField(max_length=8, choices=CHOICES)
    course = models.CharField(max_length=20, blank=True)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.name


class Offer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post')
    CHOICES = (
        ('Exchange', 'Exchange'),
        ('Purchase', 'Purchase'),
    )
    type = models.CharField(max_length=8, choices=CHOICES)
    amount = models.DecimalField(decimal_places=2, blank=True, max_digits=20, null=True)
    secondhand = models.ForeignKey(Post, null=True, blank=True, related_name='secondhand')
    approve_reject = models.NullBooleanField(blank=True, null=True)
    reason = models.CharField(blank=True, null=True, max_length=255)

    def __str__(self):
        return self.post.name

mp2/marketplace/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from marketplace.models import Post, Offer


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    degree_or_office = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2',
            'degree_or_office',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.degree_or_office = self.cleaned_data['degree_or_office']

        if commit:
            user.save()

        return user


class PostForm(forms.ModelForm):
    name = forms.CharField(required=True)
    condition = forms.CharField(required=True)
    type = forms.ChoiceField(choices=Post.CHOICES, required=True)
    quantity = forms.IntegerField(required=True, initial='1', min_value=1)

    class Meta:
        model = Post
        fields = (
            'image',
            'name',
            'condition',
            'quantity',
            'type',
            'course',
            'tags',
        )

    def save(self, commit=True):
        post = super(PostForm, self).save(commit=False)
        post.name = self.cleaned_data['name']
        post.condition = self.cleaned_data['condition']
        post.type = self.cleaned_data['type']
        post.quantity = self.cleaned_data['quantity']

        if commit:
            post.save()

        return post


class OfferForm(forms.ModelForm):
    type = forms.ChoiceField(choices=Offer.CHOICES, required=True)

    class Meta:
        model = Offer
        fields = (
            'type',
            'amount',
            'secondhand',
        )

    def save(self, commit=True):
        offer = super(OfferForm, self).save(commit=False)
        offer.type = self.cleaned_data['type']
        offer.amount = self.cleaned_data['amount']
        offer.secondhand = self.cleaned_data['secondhand']

        if commit:
            offer.save()

        return offer
#
#
# class AcceptRejectForm(forms.ModelForm):
#     reason = forms.CharField(required=True, max_length=255)
#
#     class Meta:
#         model = Offer
#         fields = (
#             'reason',
#             'approve_reject',
#         )
#
#     def save(self, commit=True):
#         offer = super(AcceptRejectForm, self).save(commit=False)
#         offer.reason = self.cleaned_data['reason']
#         offer.approve_reject = self.cleaned_data['approve_reject']
#
#         if commit:
#             offer.save()
#
#         return offer

mp2/marketplace/views.py
from django.shortcuts import render, get_object_or_404, redirect
from marketplace.forms import RegistrationForm, PostForm, OfferForm #, AcceptRejectForm
from django.contrib.auth.views import login
from .models import User, Post, Offer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    latest_post_list = Post.objects.all().order_by('-id')

    if request.user.is_authenticated():
        offers = Offer.objects.filter(user=request.user)
        offers2 = Offer.objects.filter(post__in=Post.objects.filter(user=request.user).order_by('-id'))
    else:
        offers = None
        offers2 = None

    search = request.GET.get('query')
    page = request.GET.get('page')
    itemnum = request.GET.get('c')

    if search:
        latest_post_list = latest_post_list.filter(tags__name__in=[search]).distinct()
    paginator = Paginator(latest_post_list, 10)

    if itemnum:
        paginator = Paginator(latest_post_list, itemnum)

    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'latest_post_list': latest_post_list,
                'regform': regform,
                'postform': postform,
                'offers': offers,
                'offers2': offers2,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        postform = PostForm()
        regform = RegistrationForm()
        try:
            latest_post_list = paginator.page(page)
        except PageNotAnInteger:
            latest_post_list = paginator.page(1)
        except EmptyPage:
            latest_post_list = paginator.page(paginator.num_pages)
        context = {
            'latest_post_list': latest_post_list,
            'regform': regform,
            'postform': postform,
            'offers': offers,
            'offers2': offers2,
        }
        return render(request, 'marketplace/index.html', context)


def userdetails(request, user_id):
    userobj = get_object_or_404(User, pk=user_id)
    user_latest_post = Post.objects.filter(user=userobj).order_by('-id')
    offers = Offer.objects.filter(post__in=user_latest_post).order_by('-id')
    myoffers = Offer.objects.filter(user=request.user, post__in=user_latest_post).order_by('-id')

    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'userprofile': userobj,
                'latest_posts': user_latest_post,
                'regform': regform,
                'postform': postform,
                'offers': offers,
                'myoffers': myoffers,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        context = {
            'userprofile': userobj,
            'latest_posts': user_latest_post,
            'regform': regform,
            'postform': postform,
            'offers': offers,
            'myoffers': myoffers,
        }
        return render(request, 'marketplace/user.html', context)


def makeoffer(request, post_id):
    userobj = request.user
    latest_post_list = Post.objects.filter(user=userobj).order_by('-id')
    postobj = Post.objects.filter(id=post_id)[:1].get()

    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        offerform = OfferForm(request.POST)

        if offerform.is_valid():
            offerobj = offerform.save(commit=False)
            offerobj.user = request.user
            offerobj.post = Post.objects.filter(id=post_id)[:1].get()
            offerobj.save()
            return redirect('/')
        elif regform.is_valid():
            regform.save()
            return redirect('/')
        elif postform.is_valid():
            obj = postform.save(commit=False)
            obj.user = request.user
            obj.image = postform.cleaned_data['image']
            obj.save()
            postform.save_m2m()
            return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            offerform = OfferForm()
            context = {
                'regform': regform,
                'postform': postform,
                'offerform': offerform,
                'posts': latest_post_list,
                'postobj': postobj,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        offerform = OfferForm()
        context = {
            'regform': regform,
            'postform': postform,
            'offerform': offerform,
            'posts': latest_post_list,
            'postobj': postobj,
        }
        return render(request, 'marketplace/offer.html', context)


def canceloffer(request, myoffer_id):
    myofferobj = Offer.objects.filter(id=myoffer_id)[:1].get()
    myofferobj.delete()
    return redirect('/')


def updateoffer(request, myoffer_id):
    myofferobj = Offer.objects.filter(id=myoffer_id)[:1].get()
    postobj = Post.objects.filter(id=myofferobj.post.id)[:1].get()
    myofferobj.delete()
    return redirect('/' + 'offer/' + str(postobj.id) + '/')


def approveoffer(request, offer_id):
    offerobj = Offer.objects.filter(id=offer_id)[:1].get()

    offerobj.approve_reject = True
    offerobj.reason = request.POST.get("reasonA", "")
    offerobj.save()
    return redirect('/')


def rejectoffer(request, offer_id):
    offerobj = Offer.objects.filter(id=offer_id)[:1].get()

    offerobj.approve_reject = False
    offerobj.reason = request.POST.get("reasonR", "")
    offerobj.save()
    return redirect('/')


def photo(request, post_id):
    postobj = Post.objects.filter(id=post_id)
    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'post': postobj,
                'regform': regform,
                'postform': postform,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        context = {
            'post': postobj,
            'regform': regform,
            'postform': postform,
        }
        return render(request, 'marketplace/image.html', context)


def condresults(request, condition_name):
    postobj = Post.objects.filter(condition=condition_name)
    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'query_item': condition_name,
                'post': postobj,
                'regform': regform,
                'postform': postform,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        context = {
            'query_item': condition_name,
            'post': postobj,
            'regform': regform,
            'postform': postform,
        }
        return render(request, 'marketplace/results.html', context)


def typeresults(request, type_name):
    postobj = Post.objects.filter(type=type_name)
    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user

mp2/marketplace/templates/marketplace/includes/header.html
{% load staticfiles %}
<head>
    {% block head %}
        <link type="text/css" rel="stylesheet" href="{% static "marketplace/css/bootstrap.min.css" %}"/>
        <link type="text/css" rel="stylesheet" href="{% static "marketplace/css/edited.css" %}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static "marketplace/js/bootstrap.min.js" %}"></script>
        <title>{% block title %}New Beginnings Marketplace{% endblock %}</title>
        {% block script %}{% endblock %}
    {% endblock %}
</head>
{% block header %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'marketplace:index' %}"><span class="glyphicon glyphicon-ice-lolly-tasted" aria-hidden="true"></span> New Beginnings Marketplace</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query" value = "{{ request.GET.query }}" placeholder="Search tags..." >
                        <button type="submit" class="btn btn-default">Search</button>
                    </div>
                </form>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><button data-toggle="modal" data-target="#postModal" class="btn btn-primary navbar-btn">Post a second hand item</button></li>
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Logged in as {{ user.get_username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'marketplace:userdetails' user.id %}">My Profile</a></li>
                                <li><a href="{% url 'marketplace:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                {% endif %}
                {% if not user.is_authenticated %}
                    <ul id="navforms" class="nav navbar-nav navbar-right">
                        <li><button data-toggle="modal" data-target="#loginModal" class="btn btn-default navbar-btn" style="margin-right:10px;">Log In</button></li>
                        <li><button data-toggle="modal" data-target="#signupModal" class="btn btn-primary navbar-btn" style="margin-right:10px;">Sign Up</button></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Log In</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-user"></span>
                                </span>
                                <input type="text" id="id_username" name="username" class="form-control input-sm" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-lock"></span>
                                </span>
                                <input type="password" id="id_password" name="password" class="form-control input-sm" placeholder="Password">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Log In</button>
                        <input type="hidden" name="next" value="{{ next }}">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="signupModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Sign Up <small>It's free!</small></h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" id="id_first_name" name="first_name" class="form-control input-sm" placeholder="First Name">
                        </div>
                        <div class="form-group">
                            <input type="text" id="id_last_name" name="last_name" class="form-control input-sm" placeholder="Last Name">
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-user"></span>
                                </span>
                                <input type="text" id="id_username" name="username" class="form-control input-sm" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-lock"></span>
                                </span>
                                <input type="password" id="id_password1" name="password1" class="form-control input-sm" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-lock"></span>
                                </span>
                                <input type="password" id="id_password2" name="password2" class="form-control input-sm" placeholder="Confirm Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="text" id="id_degree_or_office" name="degree_or_office" class="form-control input-sm" placeholder="Degree Program or Office">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                        <input type="hidden" name="next" value="{{ next }}">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="postModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Post a second hand item!</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="file" id="id_image" name="image" accept="image/*" class="form-control input-sm">
                        </div>
                        <div class="form-group">
                            <input type="text" id="id_name" name="name" class="form-control input-sm" placeholder="Title">
                        </div>
                        <div class="form-group">
                            <input type="text" id="id_condition" name="condition" class="form-control input-sm" placeholder="Condition">
                        </div>
                        <div class="form-group">
                            <input type="number" min="1" id="id_quantity" name="quantity" class="form-control input-sm" placeholder="Quantity">
                        </div>
                        <div class="form-group">
                            <select class="form-control" id="id_type" name="type">
                                <option value="Academic">Academic</option>
                                <option value="Office">Office</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" id="id_course" name="course" class="form-control input-sm" placeholder="Course (if academic)">
                        </div>
                        <div class="form-group">
                            <input type="text" id="id_tags" name="tags" class="form-control input-sm" placeholder="Tags (separated by spaces)">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Post Item</button>
                        <input type="hidden" name="next" value="{{ next }}">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block body %}{% endblock %}