mp2/marketplace/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'marketplace'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/(?P<user_id>[0-9]+)/$', views.userdetails, name='userdetails'),
    url(r'^photo/(?P<post_id>[0-9]+)/$', views.photo, name='photo'),
    url(r'^offer/(?P<post_id>[0-9]+)/$', views.makeoffer, name='makeoffer'),
    url(r'^update/(?P<myoffer_id>[0-9]+)/$', views.updateoffer, name='updateoffer'),
    url(r'^approve/(?P<offer_id>[0-9]+)/$', views.approveoffer, name='approveoffer'),
    url(r'^reject/(?P<offer_id>[0-9]+)/$', views.rejectoffer, name='rejectoffer'),
    url(r'^delete/(?P<myoffer_id>[0-9]+)/$', views.canceloffer, name='canceloffer'),
    url(r'^results/condition/(?P<condition_name>[-\w ]+)/$', views.condresults, name='condresults'),
    url(r'^results/type/(?P<type_name>\w+)/$', views.typeresults, name='typeresults'),
    url(r'^results/course/(?P<course_name>[-\w ]+)/$', views.courseresults, name='courseresults'),
    url(r'^results/tags/(?P<tag_name>[-\w]+)/$', views.tagresults, name='tagresults'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mp2/mp2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('marketplace.urls')),
]

mp2/marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from taggit.managers import TaggableManager


degree_or_office = models.CharField(max_length=50)
degree_or_office.contribute_to_class(User, 'degree_or_office')


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='marketplace/static/marketplace/img/', blank=True, default='marketplace/static/marketplace/img/def/default.png')
    name = models.CharField(max_length=25)
    condition = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    CHOICES = (
        ('Academic', 'Academic'),
        ('Office', 'Office'),
    )
    type = models.CharField(max_length=8, choices=CHOICES)
    course = models.CharField(max_length=20, blank=True)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.name


class Offer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post')
    CHOICES = (
        ('Exchange', 'Exchange'),
        ('Purchase', 'Purchase'),
    )
    type = models.CharField(max_length=8, choices=CHOICES)
    amount = models.DecimalField(decimal_places=2, blank=True, max_digits=20, null=True)
    secondhand = models.ForeignKey(Post, null=True, blank=True, related_name='secondhand')
    approve_reject = models.NullBooleanField(blank=True, null=True)
    reason = models.CharField(blank=True, null=True, max_length=255)

    def __str__(self):
        return self.post.name

mp2/marketplace/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from marketplace.models import Post, Offer


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    degree_or_office = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2',
            'degree_or_office',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.degree_or_office = self.cleaned_data['degree_or_office']

        if commit:
            user.save()

        return user


class PostForm(forms.ModelForm):
    name = forms.CharField(required=True)
    condition = forms.CharField(required=True)
    type = forms.ChoiceField(choices=Post.CHOICES, required=True)
    quantity = forms.IntegerField(required=True, initial='1', min_value=1)

    class Meta:
        model = Post
        fields = (
            'image',
            'name',
            'condition',
            'quantity',
            'type',
            'course',
            'tags',
        )

    def save(self, commit=True):
        post = super(PostForm, self).save(commit=False)
        post.name = self.cleaned_data['name']
        post.condition = self.cleaned_data['condition']
        post.type = self.cleaned_data['type']
        post.quantity = self.cleaned_data['quantity']

        if commit:
            post.save()

        return post


class OfferForm(forms.ModelForm):
    type = forms.ChoiceField(choices=Offer.CHOICES, required=True)

    class Meta:
        model = Offer
        fields = (
            'type',
            'amount',
            'secondhand',
        )

    def save(self, commit=True):
        offer = super(OfferForm, self).save(commit=False)
        offer.type = self.cleaned_data['type']
        offer.amount = self.cleaned_data['amount']
        offer.secondhand = self.cleaned_data['secondhand']

        if commit:
            offer.save()

        return offer
#
#
# class AcceptRejectForm(forms.ModelForm):
#     reason = forms.CharField(required=True, max_length=255)
#
#     class Meta:
#         model = Offer
#         fields = (
#             'reason',
#             'approve_reject',
#         )
#
#     def save(self, commit=True):
#         offer = super(AcceptRejectForm, self).save(commit=False)
#         offer.reason = self.cleaned_data['reason']
#         offer.approve_reject = self.cleaned_data['approve_reject']
#
#         if commit:
#             offer.save()
#
#         return offer

mp2/marketplace/views.py
from django.shortcuts import render, get_object_or_404, redirect
from marketplace.forms import RegistrationForm, PostForm, OfferForm #, AcceptRejectForm
from django.contrib.auth.views import login
from .models import User, Post, Offer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    latest_post_list = Post.objects.all().order_by('-id')

    if request.user.is_authenticated():
        offers = Offer.objects.filter(user=request.user)
        offers2 = Offer.objects.filter(post__in=Post.objects.filter(user=request.user).order_by('-id'))
    else:
        offers = None
        offers2 = None

    search = request.GET.get('query')
    page = request.GET.get('page')
    itemnum = request.GET.get('c')

    if search:
        latest_post_list = latest_post_list.filter(tags__name__in=[search]).distinct()
    paginator = Paginator(latest_post_list, 10)

    if itemnum:
        paginator = Paginator(latest_post_list, itemnum)

    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'latest_post_list': latest_post_list,
                'regform': regform,
                'postform': postform,
                'offers': offers,
                'offers2': offers2,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        postform = PostForm()
        regform = RegistrationForm()
        try:
            latest_post_list = paginator.page(page)
        except PageNotAnInteger:
            latest_post_list = paginator.page(1)
        except EmptyPage:
            latest_post_list = paginator.page(paginator.num_pages)
        context = {
            'latest_post_list': latest_post_list,
            'regform': regform,
            'postform': postform,
            'offers': offers,
            'offers2': offers2,
        }
        return render(request, 'marketplace/index.html', context)


def userdetails(request, user_id):
    userobj = get_object_or_404(User, pk=user_id)
    user_latest_post = Post.objects.filter(user=userobj).order_by('-id')
    offers = Offer.objects.filter(post__in=user_latest_post).order_by('-id')
    myoffers = Offer.objects.filter(user=request.user, post__in=user_latest_post).order_by('-id')

    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'userprofile': userobj,
                'latest_posts': user_latest_post,
                'regform': regform,
                'postform': postform,
                'offers': offers,
                'myoffers': myoffers,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        context = {
            'userprofile': userobj,
            'latest_posts': user_latest_post,
            'regform': regform,
            'postform': postform,
            'offers': offers,
            'myoffers': myoffers,
        }
        return render(request, 'marketplace/user.html', context)


def makeoffer(request, post_id):
    userobj = request.user
    latest_post_list = Post.objects.filter(user=userobj).order_by('-id')
    postobj = Post.objects.filter(id=post_id)[:1].get()

    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        offerform = OfferForm(request.POST)

        if offerform.is_valid():
            offerobj = offerform.save(commit=False)
            offerobj.user = request.user
            offerobj.post = Post.objects.filter(id=post_id)[:1].get()
            offerobj.save()
            return redirect('/')
        elif regform.is_valid():
            regform.save()
            return redirect('/')
        elif postform.is_valid():
            obj = postform.save(commit=False)
            obj.user = request.user
            obj.image = postform.cleaned_data['image']
            obj.save()
            postform.save_m2m()
            return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            offerform = OfferForm()
            context = {
                'regform': regform,
                'postform': postform,
                'offerform': offerform,
                'posts': latest_post_list,
                'postobj': postobj,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        offerform = OfferForm()
        context = {
            'regform': regform,
            'postform': postform,
            'offerform': offerform,
            'posts': latest_post_list,
            'postobj': postobj,
        }
        return render(request, 'marketplace/offer.html', context)


def canceloffer(request, myoffer_id):
    myofferobj = Offer.objects.filter(id=myoffer_id)[:1].get()
    myofferobj.delete()
    return redirect('/')


def updateoffer(request, myoffer_id):
    myofferobj = Offer.objects.filter(id=myoffer_id)[:1].get()
    postobj = Post.objects.filter(id=myofferobj.post.id)[:1].get()
    myofferobj.delete()
    return redirect('/' + 'offer/' + str(postobj.id) + '/')


def approveoffer(request, offer_id):
    offerobj = Offer.objects.filter(id=offer_id)[:1].get()

    offerobj.approve_reject = True
    offerobj.reason = request.POST.get("reasonA", "")
    offerobj.save()
    return redirect('/')


def rejectoffer(request, offer_id):
    offerobj = Offer.objects.filter(id=offer_id)[:1].get()

    offerobj.approve_reject = False
    offerobj.reason = request.POST.get("reasonR", "")
    offerobj.save()
    return redirect('/')


def photo(request, post_id):
    postobj = Post.objects.filter(id=post_id)
    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'post': postobj,
                'regform': regform,
                'postform': postform,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        context = {
            'post': postobj,
            'regform': regform,
            'postform': postform,
        }
        return render(request, 'marketplace/image.html', context)


def condresults(request, condition_name):
    postobj = Post.objects.filter(condition=condition_name)
    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user
                obj.image = postform.cleaned_data['image']
                obj.save()
                postform.save_m2m()
                return redirect('/')
        else:
            postform = PostForm()
            regform = RegistrationForm()
            context = {
                'query_item': condition_name,
                'post': postobj,
                'regform': regform,
                'postform': postform,
            }
            return login(request, context, template_name='marketplace/err.html')
    else:
        regform = RegistrationForm()
        postform = PostForm()
        context = {
            'query_item': condition_name,
            'post': postobj,
            'regform': regform,
            'postform': postform,
        }
        return render(request, 'marketplace/results.html', context)


def typeresults(request, type_name):
    postobj = Post.objects.filter(type=type_name)
    if request.method == 'POST':
        regform = RegistrationForm(request.POST)
        postform = PostForm(request.POST, request.FILES)
        if regform.is_valid():
            regform.save()
            return redirect('/')
        elif request.user.is_authenticated():
            if postform.is_valid():
                obj = postform.save(commit=False)
                obj.user = request.user

mp2/marketplace/templates/marketplace/err.html
{% extends 'marketplace/includes/header.html' %}

{% block body %}
    <div class="container">
        <div class="alert alert-danger" role="alert"><strong>ERROR!</strong></div>
    </div>
{% endblock %}

mp2/marketplace/templates/marketplace/image.html
{% extends 'marketplace/includes/header.html' %}

{% block body %}
    {% for item in post %}
        <img src='{{ item.image.url }}'>
    {% endfor %}
{% endblock %}

mp2/marketplace/templates/marketplace/offer.html
{% extends 'marketplace/includes/header.html' %}
{% block title %}
    Make an Offer
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            var idamount = $('#amountdiv');
            var idsecondhand = $('#secondhanddiv');
            idsecondhand.hide();

            $('.typeselect').change(function () {
                if ($('.typeselect').val() === 'Exchange') {
                    idsecondhand.show();
                    $('#secondhanddiv select').val($('#secondhanddiv select option:first').val());
                    $('#amountdiv div input').val(null);
                    idamount.hide();
                }
                if ($('.typeselect').val() === 'Purchase') {
                    idsecondhand.hide();
                    $('#secondhanddiv select').val(null);
                    idamount.show();
                }
            });
        });
    </script>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Make an Offer for {{ postobj.name }}</h4>
                    </div>

                    <form role="form" method="post">
                        {% csrf_token %}
                        <div class="panel-body">
                            <div class="form-group">
                                <select class="form-control typeselect" id="id_type" name="type">
                                    <option value="Purchase">Purchase</option>
                                    <option value="Exchange">Exchange</option>
                                </select>
                            </div>
                            <div id="amountdiv" class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-usd"></span>
                                    </span>
                                    <input type="number" min="0.01" step="0.01" max="999999999999999999.99" id="id_amount" name="amount" class="form-control input-sm" placeholder="Amount">
                                </div>
                            </div>
                            <div id="secondhanddiv" class="form-group">
                                <select class="form-control" id="id_secondhand" name="secondhand">
                                    {% for post in posts %}
                                        <option value="{{ post.id }}">{{ post.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mp2/marketplace/templates/marketplace/results.html
{% extends 'marketplace/includes/header.html' %}

{% block body %}
    <div class="container">
        <div class="col-md-12 col-sm-12" >
            <h4>Filtered item: <strong>{{ query_item }}</strong></h4>
        </div>
        <div class="row">
            {% for p in post %}
                <div class="col-sm-6 col-md-3">
                        <div class="thumbnail">
                            <a data-toggle="modal" data-target="#postModal{{ p.id }}" href="javascript:void(0);"><img src="{{ p.image.url }}" style="height:200px;"></a>
                            <div class="caption" style="height: 120px;">
                                <h3 class="panel-title"><a data-toggle="modal" data-target="#postModal{{ p.id }}" href="javascript:void(0);">{{ p.name }}</a></h3>
                                <p><a href="{% url 'marketplace:userdetails' p.user.id %}">
                                    {{ p.user }}
                                </a></p>
                                <p><small>Tags:
                                    {% for t in p.tags.all %}
                                        <a href="{% url 'marketplace:tagresults' t.name %}">{{ t.name }}</a>
                                    {% endfor %}
                                </small></p>
                            </div>
                        </div>
                    </div>

                    <div class="modal fade" id="postModal{{ p.id }}" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title">{{ p.name }}</h4>
                                </div>
                                <div class="modal-body">
                                    <a href="{% url 'marketplace:photo' p.id %}"><img class="center-block" src="{{ p.image.url }}" height="245px"></a>
                                </div>
                                <div class="modal-footer" style="text-align: left">
                                    <h4><strong>Quantity</strong></h4>
                                    <p>{{ p.quantity }}</p>
                                    <h4><strong>Condition</strong></h4>
                                    <p><a href="{% url 'marketplace:condresults' p.condition %}">{{ p.condition }}</a></p>
                                    <h4><strong>Type</strong></h4>
                                    <p><a href="{% url 'marketplace:typeresults' p.type %}">{{ p.type }}</a></p>
                                    {% if p.course %}
                                        <h4><strong>Course</strong></h4>
                                        <p><a href="{% url 'marketplace:courseresults' p.course %}">{{ p.course }}</a></p>
                                    {% endif %}
                                    <h4><strong>Tags</strong></h4>
                                    <p>{% for t in p.tags.all %}
                                        <a href="{% url 'marketplace:tagresults' t.name %}">{{ t.name }}</a>
                                    {% endfor %}</p>
                                    <h4><strong>User</strong></h4>
                                    <p><a href="{% url 'marketplace:userdetails' p.user.id %}">
                                        {{ p.user }}
                                    </a></p>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}